/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTVSETTINGS_H
#define _MOCKTVSETTINGS_H

#include "unity.h"
#include "tvSettings.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MocktvSettings_Init(void);
void MocktvSettings_Destroy(void);
void MocktvSettings_Verify(void);




#define tvInit_ExpectAndReturn(cmock_retval) tvInit_CMockExpectAndReturn(__LINE__, cmock_retval)
void tvInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvError_t cmock_to_return);
#define tvSD3toCriSyncInit_ExpectAndReturn(cmock_retval) tvSD3toCriSyncInit_CMockExpectAndReturn(__LINE__, cmock_retval)
void tvSD3toCriSyncInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvError_t cmock_to_return);
#define tvTerm_ExpectAndReturn(cmock_retval) tvTerm_CMockExpectAndReturn(__LINE__, cmock_retval)
void tvTerm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvError_t cmock_to_return);
#define GetTVPictureMode_ExpectAndReturn(pictureMode, cmock_retval) GetTVPictureMode_CMockExpectAndReturn(__LINE__, pictureMode, cmock_retval)
void GetTVPictureMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* pictureMode, tvError_t cmock_to_return);
#define SetTVPictureMode_ExpectAndReturn(pictureMode, cmock_retval) SetTVPictureMode_CMockExpectAndReturn(__LINE__, pictureMode, cmock_retval)
void SetTVPictureMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* pictureMode, tvError_t cmock_to_return);
#define GetBacklight_ExpectAndReturn(backlight, cmock_retval) GetBacklight_CMockExpectAndReturn(__LINE__, backlight, cmock_retval)
void GetBacklight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* backlight, tvError_t cmock_to_return);
#define SetBacklight_ExpectAndReturn(backlight, cmock_retval) SetBacklight_CMockExpectAndReturn(__LINE__, backlight, cmock_retval)
void SetBacklight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int backlight, tvError_t cmock_to_return);
#define SetBrightness_ExpectAndReturn(brightness, cmock_retval) SetBrightness_CMockExpectAndReturn(__LINE__, brightness, cmock_retval)
void SetBrightness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int brightness, tvError_t cmock_to_return);
#define GetBrightness_ExpectAndReturn(brightness, cmock_retval) GetBrightness_CMockExpectAndReturn(__LINE__, brightness, cmock_retval)
void GetBrightness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* brightness, tvError_t cmock_to_return);
#define SetContrast_ExpectAndReturn(contrast, cmock_retval) SetContrast_CMockExpectAndReturn(__LINE__, contrast, cmock_retval)
void SetContrast_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int contrast, tvError_t cmock_to_return);
#define GetContrast_ExpectAndReturn(contrast, cmock_retval) GetContrast_CMockExpectAndReturn(__LINE__, contrast, cmock_retval)
void GetContrast_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* contrast, tvError_t cmock_to_return);
#define SetSharpness_ExpectAndReturn(sharpness, cmock_retval) SetSharpness_CMockExpectAndReturn(__LINE__, sharpness, cmock_retval)
void SetSharpness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sharpness, tvError_t cmock_to_return);
#define GetSharpness_ExpectAndReturn(sharpness, cmock_retval) GetSharpness_CMockExpectAndReturn(__LINE__, sharpness, cmock_retval)
void GetSharpness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* sharpness, tvError_t cmock_to_return);
#define SetSaturation_ExpectAndReturn(saturation, cmock_retval) SetSaturation_CMockExpectAndReturn(__LINE__, saturation, cmock_retval)
void SetSaturation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int saturation, tvError_t cmock_to_return);
#define GetSaturation_ExpectAndReturn(saturation, cmock_retval) GetSaturation_CMockExpectAndReturn(__LINE__, saturation, cmock_retval)
void GetSaturation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* saturation, tvError_t cmock_to_return);
#define SetHue_ExpectAndReturn(hue, cmock_retval) SetHue_CMockExpectAndReturn(__LINE__, hue, cmock_retval)
void SetHue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int hue, tvError_t cmock_to_return);
#define GetHue_ExpectAndReturn(hue, cmock_retval) GetHue_CMockExpectAndReturn(__LINE__, hue, cmock_retval)
void GetHue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* hue, tvError_t cmock_to_return);
#define SetColorTemperature_ExpectAndReturn(colorTemp, cmock_retval) SetColorTemperature_CMockExpectAndReturn(__LINE__, colorTemp, cmock_retval)
void SetColorTemperature_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, tvError_t cmock_to_return);
#define GetColorTemperature_ExpectAndReturn(colorTemp, cmock_retval) GetColorTemperature_CMockExpectAndReturn(__LINE__, colorTemp, cmock_retval)
void GetColorTemperature_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t* colorTemp, tvError_t cmock_to_return);
#define SetAspectRatio_ExpectAndReturn(dispMode, cmock_retval) SetAspectRatio_CMockExpectAndReturn(__LINE__, dispMode, cmock_retval)
void SetAspectRatio_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDisplayMode_t dispMode, tvError_t cmock_to_return);
#define GetAspectRatio_ExpectAndReturn(dispMode, cmock_retval) GetAspectRatio_CMockExpectAndReturn(__LINE__, dispMode, cmock_retval)
void GetAspectRatio_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDisplayMode_t* dispMode, tvError_t cmock_to_return);
#define GetTint_ExpectAndReturn(tint, cmock_retval) GetTint_CMockExpectAndReturn(__LINE__, tint, cmock_retval)
void GetTint_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* tint, tvError_t cmock_to_return);
#define SetTint_ExpectAndReturn(tint, cmock_retval) SetTint_CMockExpectAndReturn(__LINE__, tint, cmock_retval)
void SetTint_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int tint, tvError_t cmock_to_return);
#define GetSupportedBacklightModes_ExpectAndReturn(blModes, cmock_retval) GetSupportedBacklightModes_CMockExpectAndReturn(__LINE__, blModes, cmock_retval)
void GetSupportedBacklightModes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* blModes, tvError_t cmock_to_return);
#define GetCurrentBacklightMode_ExpectAndReturn(blMode, cmock_retval) GetCurrentBacklightMode_CMockExpectAndReturn(__LINE__, blMode, cmock_retval)
void GetCurrentBacklightMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvBacklightMode_t* blMode, tvError_t cmock_to_return);
#define SetCurrentBacklightMode_ExpectAndReturn(blMode, cmock_retval) SetCurrentBacklightMode_CMockExpectAndReturn(__LINE__, blMode, cmock_retval)
void SetCurrentBacklightMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvBacklightMode_t blMode, tvError_t cmock_to_return);
#define GetCurrentVideoFormat_ExpectAndReturn(format, cmock_retval) GetCurrentVideoFormat_CMockExpectAndReturn(__LINE__, format, cmock_retval)
void GetCurrentVideoFormat_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvVideoHDRFormat_t* format, tvError_t cmock_to_return);
#define GetVideoResolution_ExpectAndReturn(res, cmock_retval) GetVideoResolution_CMockExpectAndReturn(__LINE__, res, cmock_retval)
void GetVideoResolution_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvResolutionParam_t* res, tvError_t cmock_to_return);
#define GetVideoFrameRate_ExpectAndReturn(format, cmock_retval) GetVideoFrameRate_CMockExpectAndReturn(__LINE__, format, cmock_retval)
void GetVideoFrameRate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvVideoFrameRate_t* format, tvError_t cmock_to_return);
#define setWakeupConfig_ExpectAndReturn(src_type, value, cmock_retval) setWakeupConfig_CMockExpectAndReturn(__LINE__, src_type, value, cmock_retval)
void setWakeupConfig_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const tvWakeupSrcType_t src_type, const bool value, tvError_t cmock_to_return);
#define SetRGBPattern_ExpectAndReturn(r, g, b, cmock_retval) SetRGBPattern_CMockExpectAndReturn(__LINE__, r, g, b, cmock_retval)
void SetRGBPattern_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int r, int g, int b, tvError_t cmock_to_return);
#define GetRGBPattern_ExpectAndReturn(r, g, b, cmock_retval) GetRGBPattern_CMockExpectAndReturn(__LINE__, r, g, b, cmock_retval)
void GetRGBPattern_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* r, int* g, int* b, tvError_t cmock_to_return);
#define SetGrayPattern_ExpectAndReturn(YUVValue, cmock_retval) SetGrayPattern_CMockExpectAndReturn(__LINE__, YUVValue, cmock_retval)
void SetGrayPattern_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int YUVValue, tvError_t cmock_to_return);
#define GetGrayPattern_ExpectAndReturn(YUVValue, cmock_retval) GetGrayPattern_CMockExpectAndReturn(__LINE__, YUVValue, cmock_retval)
void GetGrayPattern_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* YUVValue, tvError_t cmock_to_return);
#define SetColorTemp_Rgain_ExpectAndReturn(colorTemp, rgain, cmock_retval) SetColorTemp_Rgain_CMockExpectAndReturn(__LINE__, colorTemp, rgain, cmock_retval)
void SetColorTemp_Rgain_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int rgain, tvError_t cmock_to_return);
#define GetColorTemp_Rgain_ExpectAndReturn(colorTemp, rgain, cmock_retval) GetColorTemp_Rgain_CMockExpectAndReturn(__LINE__, colorTemp, rgain, cmock_retval)
void GetColorTemp_Rgain_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* rgain, tvError_t cmock_to_return);
#define SetColorTemp_Ggain_ExpectAndReturn(colorTemp, ggain, cmock_retval) SetColorTemp_Ggain_CMockExpectAndReturn(__LINE__, colorTemp, ggain, cmock_retval)
void SetColorTemp_Ggain_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int ggain, tvError_t cmock_to_return);
#define GetColorTemp_Ggain_ExpectAndReturn(colorTemp, ggain, cmock_retval) GetColorTemp_Ggain_CMockExpectAndReturn(__LINE__, colorTemp, ggain, cmock_retval)
void GetColorTemp_Ggain_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* ggain, tvError_t cmock_to_return);
#define SetColorTemp_Bgain_ExpectAndReturn(colorTemp, bgain, cmock_retval) SetColorTemp_Bgain_CMockExpectAndReturn(__LINE__, colorTemp, bgain, cmock_retval)
void SetColorTemp_Bgain_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int bgain, tvError_t cmock_to_return);
#define GetColorTemp_Bgain_ExpectAndReturn(colorTemp, bgain, cmock_retval) GetColorTemp_Bgain_CMockExpectAndReturn(__LINE__, colorTemp, bgain, cmock_retval)
void GetColorTemp_Bgain_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* bgain, tvError_t cmock_to_return);
#define SetColorTemp_R_post_offset_ExpectAndReturn(colorTemp, rpostoffset, cmock_retval) SetColorTemp_R_post_offset_CMockExpectAndReturn(__LINE__, colorTemp, rpostoffset, cmock_retval)
void SetColorTemp_R_post_offset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int rpostoffset, tvError_t cmock_to_return);
#define GetColorTemp_R_post_offset_ExpectAndReturn(colorTemp, rpostoffset, cmock_retval) GetColorTemp_R_post_offset_CMockExpectAndReturn(__LINE__, colorTemp, rpostoffset, cmock_retval)
void GetColorTemp_R_post_offset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* rpostoffset, tvError_t cmock_to_return);
#define SetColorTemp_G_post_offset_ExpectAndReturn(colorTemp, gpostoffset, cmock_retval) SetColorTemp_G_post_offset_CMockExpectAndReturn(__LINE__, colorTemp, gpostoffset, cmock_retval)
void SetColorTemp_G_post_offset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int gpostoffset, tvError_t cmock_to_return);
#define GetColorTemp_G_post_offset_ExpectAndReturn(colorTemp, gpostoffset, cmock_retval) GetColorTemp_G_post_offset_CMockExpectAndReturn(__LINE__, colorTemp, gpostoffset, cmock_retval)
void GetColorTemp_G_post_offset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* gpostoffset, tvError_t cmock_to_return);
#define SetColorTemp_B_post_offset_ExpectAndReturn(colorTemp, bpostoffset, cmock_retval) SetColorTemp_B_post_offset_CMockExpectAndReturn(__LINE__, colorTemp, bpostoffset, cmock_retval)
void SetColorTemp_B_post_offset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int bpostoffset, tvError_t cmock_to_return);
#define GetColorTemp_B_post_offset_ExpectAndReturn(colorTemp, bpostoffset, cmock_retval) GetColorTemp_B_post_offset_CMockExpectAndReturn(__LINE__, colorTemp, bpostoffset, cmock_retval)
void GetColorTemp_B_post_offset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* bpostoffset, tvError_t cmock_to_return);
#define GetTVSupportedPictureModes_ExpectAndReturn(pictureModes, count, cmock_retval) GetTVSupportedPictureModes_CMockExpectAndReturn(__LINE__, pictureModes, count, cmock_retval)
void GetTVSupportedPictureModes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, pic_modes_t** pictureModes, unsigned short* count, tvError_t cmock_to_return);
#define GetTVSupportedDVModes_ExpectAndReturn(dvModes, count, cmock_retval) GetTVSupportedDVModes_CMockExpectAndReturn(__LINE__, dvModes, count, cmock_retval)
void GetTVSupportedDVModes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, pic_modes_t** dvModes, unsigned short* count, tvError_t cmock_to_return);
#define SetTVDolbyVisionMode_ExpectAndReturn(dolbyMode, cmock_retval) SetTVDolbyVisionMode_CMockExpectAndReturn(__LINE__, dolbyMode, cmock_retval)
void SetTVDolbyVisionMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* dolbyMode, tvError_t cmock_to_return);
#define GetTVDolbyVisionMode_ExpectAndReturn(dolbyMode, cmock_retval) GetTVDolbyVisionMode_CMockExpectAndReturn(__LINE__, dolbyMode, cmock_retval)
void GetTVDolbyVisionMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* dolbyMode, tvError_t cmock_to_return);
#define SetTVHLGMode_ExpectAndReturn(hlgMode, cmock_retval) SetTVHLGMode_CMockExpectAndReturn(__LINE__, hlgMode, cmock_retval)
void SetTVHLGMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* hlgMode, tvError_t cmock_to_return);
#define SetTVHDR10Mode_ExpectAndReturn(hdr10Mode, cmock_retval) SetTVHDR10Mode_CMockExpectAndReturn(__LINE__, hdr10Mode, cmock_retval)
void SetTVHDR10Mode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* hdr10Mode, tvError_t cmock_to_return);
#define GetTVHLGMode_ExpectAndReturn(hlgMode, cmock_retval) GetTVHLGMode_CMockExpectAndReturn(__LINE__, hlgMode, cmock_retval)
void GetTVHLGMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* hlgMode, tvError_t cmock_to_return);
#define GetTVHDR10Mode_ExpectAndReturn(hdr10Mode, cmock_retval) GetTVHDR10Mode_CMockExpectAndReturn(__LINE__, hdr10Mode, cmock_retval)
void GetTVHDR10Mode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* hdr10Mode, tvError_t cmock_to_return);
#define GetTVSupportedHLGModes_ExpectAndReturn(dvModes, count, cmock_retval) GetTVSupportedHLGModes_CMockExpectAndReturn(__LINE__, dvModes, count, cmock_retval)
void GetTVSupportedHLGModes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, pic_modes_t** dvModes, unsigned short* count, tvError_t cmock_to_return);
#define GetTVSupportedHDR10Modes_ExpectAndReturn(dvModes, count, cmock_retval) GetTVSupportedHDR10Modes_CMockExpectAndReturn(__LINE__, dvModes, count, cmock_retval)
void GetTVSupportedHDR10Modes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, pic_modes_t** dvModes, unsigned short* count, tvError_t cmock_to_return);
#define SetDynamicContrast_ExpectAndReturn(dynamicContrastEnable, cmock_retval) SetDynamicContrast_CMockExpectAndReturn(__LINE__, dynamicContrastEnable, cmock_retval)
void SetDynamicContrast_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* dynamicContrastEnable, tvError_t cmock_to_return);
#define GetDynamicContrast_ExpectAndReturn(isDynamicContrastEnabled, cmock_retval) GetDynamicContrast_CMockExpectAndReturn(__LINE__, isDynamicContrastEnabled, cmock_retval)
void GetDynamicContrast_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* isDynamicContrastEnabled, tvError_t cmock_to_return);
#define SetColorTemp_Rgain_onSource_ExpectAndReturn(colorTemp, rgain, sourceId, saveOnly, cmock_retval) SetColorTemp_Rgain_onSource_CMockExpectAndReturn(__LINE__, colorTemp, rgain, sourceId, saveOnly, cmock_retval)
void SetColorTemp_Rgain_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int rgain, int sourceId, int saveOnly, tvError_t cmock_to_return);
#define GetColorTemp_Rgain_onSource_ExpectAndReturn(colorTemp, rgain, sourceId, cmock_retval) GetColorTemp_Rgain_onSource_CMockExpectAndReturn(__LINE__, colorTemp, rgain, sourceId, cmock_retval)
void GetColorTemp_Rgain_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* rgain, int sourceId, tvError_t cmock_to_return);
#define SetColorTemp_Ggain_onSource_ExpectAndReturn(colorTemp, ggain, sourceId, saveOnly, cmock_retval) SetColorTemp_Ggain_onSource_CMockExpectAndReturn(__LINE__, colorTemp, ggain, sourceId, saveOnly, cmock_retval)
void SetColorTemp_Ggain_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int ggain, int sourceId, int saveOnly, tvError_t cmock_to_return);
#define GetColorTemp_Ggain_onSource_ExpectAndReturn(colorTemp, ggain, sourceId, cmock_retval) GetColorTemp_Ggain_onSource_CMockExpectAndReturn(__LINE__, colorTemp, ggain, sourceId, cmock_retval)
void GetColorTemp_Ggain_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* ggain, int sourceId, tvError_t cmock_to_return);
#define SetColorTemp_Bgain_onSource_ExpectAndReturn(colorTemp, bgain, sourceId, saveOnly, cmock_retval) SetColorTemp_Bgain_onSource_CMockExpectAndReturn(__LINE__, colorTemp, bgain, sourceId, saveOnly, cmock_retval)
void SetColorTemp_Bgain_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int bgain, int sourceId, int saveOnly, tvError_t cmock_to_return);
#define GetColorTemp_Bgain_onSource_ExpectAndReturn(colorTemp, bgain, sourceId, cmock_retval) GetColorTemp_Bgain_onSource_CMockExpectAndReturn(__LINE__, colorTemp, bgain, sourceId, cmock_retval)
void GetColorTemp_Bgain_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* bgain, int sourceId, tvError_t cmock_to_return);
#define SetColorTemp_R_post_offset_onSource_ExpectAndReturn(colorTemp, rpostoffset, sourceId, saveOnly, cmock_retval) SetColorTemp_R_post_offset_onSource_CMockExpectAndReturn(__LINE__, colorTemp, rpostoffset, sourceId, saveOnly, cmock_retval)
void SetColorTemp_R_post_offset_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int rpostoffset, int sourceId, int saveOnly, tvError_t cmock_to_return);
#define GetColorTemp_R_post_offset_onSource_ExpectAndReturn(colorTemp, rpostoffset, sourceId, cmock_retval) GetColorTemp_R_post_offset_onSource_CMockExpectAndReturn(__LINE__, colorTemp, rpostoffset, sourceId, cmock_retval)
void GetColorTemp_R_post_offset_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* rpostoffset, int sourceId, tvError_t cmock_to_return);
#define SetColorTemp_G_post_offset_onSource_ExpectAndReturn(colorTemp, gpostoffset, sourceId, saveOnly, cmock_retval) SetColorTemp_G_post_offset_onSource_CMockExpectAndReturn(__LINE__, colorTemp, gpostoffset, sourceId, saveOnly, cmock_retval)
void SetColorTemp_G_post_offset_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int gpostoffset, int sourceId, int saveOnly, tvError_t cmock_to_return);
#define GetColorTemp_G_post_offset_onSource_ExpectAndReturn(colorTemp, gpostoffset, sourceId, cmock_retval) GetColorTemp_G_post_offset_onSource_CMockExpectAndReturn(__LINE__, colorTemp, gpostoffset, sourceId, cmock_retval)
void GetColorTemp_G_post_offset_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* gpostoffset, int sourceId, tvError_t cmock_to_return);
#define SetColorTemp_B_post_offset_onSource_ExpectAndReturn(colorTemp, bpostoffset, sourceId, saveOnly, cmock_retval) SetColorTemp_B_post_offset_onSource_CMockExpectAndReturn(__LINE__, colorTemp, bpostoffset, sourceId, saveOnly, cmock_retval)
void SetColorTemp_B_post_offset_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int bpostoffset, int sourceId, int saveOnly, tvError_t cmock_to_return);
#define GetColorTemp_B_post_offset_onSource_ExpectAndReturn(colorTemp, bpostoffset, sourceId, cmock_retval) GetColorTemp_B_post_offset_onSource_CMockExpectAndReturn(__LINE__, colorTemp, bpostoffset, sourceId, cmock_retval)
void GetColorTemp_B_post_offset_onSource_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvColorTemp_t colorTemp, int* bpostoffset, int sourceId, tvError_t cmock_to_return);
#define setWBctrl_ExpectAndReturn(inputSrc, colorTemp, color, ctrl, value, cmock_retval) setWBctrl_CMockExpectAndReturn(__LINE__, inputSrc, colorTemp, color, ctrl, value, cmock_retval)
void setWBctrl_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* inputSrc, char* colorTemp, char* color, char* ctrl, int value, tvError_t cmock_to_return);
#define getWBctrl_ExpectAndReturn(inputSrc, colortemp, color, ctrl, value, cmock_retval) getWBctrl_CMockExpectAndReturn(__LINE__, inputSrc, colortemp, color, ctrl, value, cmock_retval)
void getWBctrl_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* inputSrc, char* colortemp, char* color, char* ctrl, int* value, tvError_t cmock_to_return);
#define enableWBmode_ExpectAndReturn(value, cmock_retval) enableWBmode_CMockExpectAndReturn(__LINE__, value, cmock_retval)
void enableWBmode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool value, tvError_t cmock_to_return);
#define GetSupportedComponentColor_ExpectAndReturn(blComponentColor, cmock_retval) GetSupportedComponentColor_CMockExpectAndReturn(__LINE__, blComponentColor, cmock_retval)
void GetSupportedComponentColor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* blComponentColor, tvError_t cmock_to_return);
#define SetCurrentComponentSaturation_ExpectAndReturn(blSaturationColor, saturation, cmock_retval) SetCurrentComponentSaturation_CMockExpectAndReturn(__LINE__, blSaturationColor, saturation, cmock_retval)
void SetCurrentComponentSaturation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataComponentColor_t blSaturationColor, int saturation, tvError_t cmock_to_return);
#define GetCurrentComponentSaturation_ExpectAndReturn(blSaturationColor, saturation, cmock_retval) GetCurrentComponentSaturation_CMockExpectAndReturn(__LINE__, blSaturationColor, saturation, cmock_retval)
void GetCurrentComponentSaturation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataComponentColor_t blSaturationColor, int* saturation, tvError_t cmock_to_return);
#define SetCurrentComponentHue_ExpectAndReturn(blHueColor, hue, cmock_retval) SetCurrentComponentHue_CMockExpectAndReturn(__LINE__, blHueColor, hue, cmock_retval)
void SetCurrentComponentHue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataComponentColor_t blHueColor, int hue, tvError_t cmock_to_return);
#define GetCurrentComponentHue_ExpectAndReturn(blHueColor, hue, cmock_retval) GetCurrentComponentHue_CMockExpectAndReturn(__LINE__, blHueColor, hue, cmock_retval)
void GetCurrentComponentHue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataComponentColor_t blHueColor, int* hue, tvError_t cmock_to_return);
#define SetCurrentComponentLuma_ExpectAndReturn(blLumaColor, Luma, cmock_retval) SetCurrentComponentLuma_CMockExpectAndReturn(__LINE__, blLumaColor, Luma, cmock_retval)
void SetCurrentComponentLuma_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataComponentColor_t blLumaColor, int Luma, tvError_t cmock_to_return);
#define GetCurrentComponentLuma_ExpectAndReturn(blLumaColor, Luma, cmock_retval) GetCurrentComponentLuma_CMockExpectAndReturn(__LINE__, blLumaColor, Luma, cmock_retval)
void GetCurrentComponentLuma_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataComponentColor_t blLumaColor, int* Luma, tvError_t cmock_to_return);
#define GetTVSupportedDimmingModes_ExpectAndReturn(dimmingModes, count, cmock_retval) GetTVSupportedDimmingModes_CMockExpectAndReturn(__LINE__, dimmingModes, count, cmock_retval)
void GetTVSupportedDimmingModes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char** dimmingModes, unsigned short* count, tvError_t cmock_to_return);
#define SetTVDimmingMode_ExpectAndReturn(dimmingMode, cmock_retval) SetTVDimmingMode_CMockExpectAndReturn(__LINE__, dimmingMode, cmock_retval)
void SetTVDimmingMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* dimmingMode, tvError_t cmock_to_return);
#define GetTVBacklightGlobalFactor_ExpectAndReturn(value, cmock_retval) GetTVBacklightGlobalFactor_CMockExpectAndReturn(__LINE__, value, cmock_retval)
void GetTVBacklightGlobalFactor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* value, tvError_t cmock_to_return);
#define SetTVBacklightGlobalFactor_ExpectAndReturn(value, rangeMidPointValue, cmock_retval) SetTVBacklightGlobalFactor_CMockExpectAndReturn(__LINE__, value, rangeMidPointValue, cmock_retval)
void SetTVBacklightGlobalFactor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int value, int rangeMidPointValue, tvError_t cmock_to_return);
#define GetTVPictureModeIndex_ExpectAndReturn(pictureMode, cmock_retval) GetTVPictureModeIndex_CMockExpectAndReturn(__LINE__, pictureMode, cmock_retval)
void GetTVPictureModeIndex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* pictureMode, tvPictureMode_t cmock_to_return);
#define GetCurrentContentFormat_ExpectAndReturn(cmock_retval) GetCurrentContentFormat_CMockExpectAndReturn(__LINE__, cmock_retval)
void GetCurrentContentFormat_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvVideoHDRFormat_t cmock_to_return);
#define GetSupportedContentFormats_ExpectAndReturn(contentFormats, numberOfFormats, cmock_retval) GetSupportedContentFormats_CMockExpectAndReturn(__LINE__, contentFormats, numberOfFormats, cmock_retval)
void GetSupportedContentFormats_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int* contentFormats, unsigned short* numberOfFormats, tvError_t cmock_to_return);
#define ResetBrightness_ExpectAndReturn(defaultValue, resetForAllFormats, cmock_retval) ResetBrightness_CMockExpectAndReturn(__LINE__, defaultValue, resetForAllFormats, cmock_retval)
void ResetBrightness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int defaultValue, bool resetForAllFormats, tvError_t cmock_to_return);
#define ResetContrast_ExpectAndReturn(defaultValue, resetForAllFormats, cmock_retval) ResetContrast_CMockExpectAndReturn(__LINE__, defaultValue, resetForAllFormats, cmock_retval)
void ResetContrast_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int defaultValue, bool resetForAllFormats, tvError_t cmock_to_return);
#define ResetSharpness_ExpectAndReturn(defaultValue, resetForAllFormats, cmock_retval) ResetSharpness_CMockExpectAndReturn(__LINE__, defaultValue, resetForAllFormats, cmock_retval)
void ResetSharpness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int defaultValue, bool resetForAllFormats, tvError_t cmock_to_return);
#define ResetSaturation_ExpectAndReturn(defaultValue, resetForAllFormats, cmock_retval) ResetSaturation_CMockExpectAndReturn(__LINE__, defaultValue, resetForAllFormats, cmock_retval)
void ResetSaturation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int defaultValue, bool resetForAllFormats, tvError_t cmock_to_return);
#define ResetHue_ExpectAndReturn(defaultValue, resetForAllFormats, cmock_retval) ResetHue_CMockExpectAndReturn(__LINE__, defaultValue, resetForAllFormats, cmock_retval)
void ResetHue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int defaultValue, bool resetForAllFormats, tvError_t cmock_to_return);
#define ResetBacklight_ExpectAndReturn(defaultValue, resetForAllFormats, cmock_retval) ResetBacklight_CMockExpectAndReturn(__LINE__, defaultValue, resetForAllFormats, cmock_retval)
void ResetBacklight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int defaultValue, bool resetForAllFormats, tvError_t cmock_to_return);
#define ResetColorTemperature_ExpectAndReturn(defaultValue, resetForAllFormats, cmock_retval) ResetColorTemperature_CMockExpectAndReturn(__LINE__, defaultValue, resetForAllFormats, cmock_retval)
void ResetColorTemperature_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int defaultValue, bool resetForAllFormats, tvError_t cmock_to_return);
#define ResetComponentSaturation_ExpectAndReturn(color, defaultValue, cmock_retval) ResetComponentSaturation_CMockExpectAndReturn(__LINE__, color, defaultValue, cmock_retval)
void ResetComponentSaturation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int color, int defaultValue, tvError_t cmock_to_return);
#define ResetComponentLuma_ExpectAndReturn(color, defaultValue, cmock_retval) ResetComponentLuma_CMockExpectAndReturn(__LINE__, color, defaultValue, cmock_retval)
void ResetComponentLuma_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int color, int defaultValue, tvError_t cmock_to_return);
#define ResetComponentHue_ExpectAndReturn(color, defaultValue, cmock_retval) ResetComponentHue_CMockExpectAndReturn(__LINE__, color, defaultValue, cmock_retval)
void ResetComponentHue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int color, int defaultValue, tvError_t cmock_to_return);
#define isCurrentHDRTypeIsSDR_ExpectAndReturn(cmock_retval) isCurrentHDRTypeIsSDR_CMockExpectAndReturn(__LINE__, cmock_retval)
void isCurrentHDRTypeIsSDR_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define GetPanelID_ExpectAndReturn(panelid, cmock_retval) GetPanelID_CMockExpectAndReturn(__LINE__, panelid, cmock_retval)
void GetPanelID_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* panelid, int cmock_to_return);
#define GetDefaultPanelID_Expect(panelID) GetDefaultPanelID_CMockExpect(__LINE__, panelID)
void GetDefaultPanelID_CMockExpect(UNITY_LINE_TYPE cmock_line, char* panelID);
#define SaveColorTemperature_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveColorTemperature_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveColorTemperature_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveBacklight_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveBacklight_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveBacklight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveContrast_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveContrast_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveContrast_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveSaturation_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveSaturation_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveSaturation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveSharpness_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveSharpness_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveSharpness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveBrightness_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveBrightness_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveBrightness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveHue_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveHue_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveHue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveDynamicBacklight_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveDynamicBacklight_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveDynamicBacklight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveDisplayMode_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveDisplayMode_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveDisplayMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SaveCMS_ExpectAndReturn(sourceInput, pq_mode, hdr_type, tunnel_type, color_type, value, cmock_retval) SaveCMS_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, tunnel_type, color_type, value, cmock_retval)
void SaveCMS_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int tunnel_type, int color_type, int value, tvError_t cmock_to_return);
#define SaveDolbyMode_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveDolbyMode_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveDolbyMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define GetNumberOfModesupported_ExpectAndReturn(cmock_retval) GetNumberOfModesupported_CMockExpectAndReturn(__LINE__, cmock_retval)
void GetNumberOfModesupported_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define GetCurrentPQIndex_ExpectAndReturn(cmock_retval) GetCurrentPQIndex_CMockExpectAndReturn(__LINE__, cmock_retval)
void GetCurrentPQIndex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define GetAllSupportedPicModeIndex_Expect(pic_mode_index) GetAllSupportedPicModeIndex_CMockExpect(__LINE__, pic_mode_index)
void GetAllSupportedPicModeIndex_CMockExpect(UNITY_LINE_TYPE cmock_line, int* pic_mode_index);
#define GetCMSDefault_ExpectAndReturn(color_tunel_type, cmock_retval) GetCMSDefault_CMockExpectAndReturn(__LINE__, color_tunel_type, cmock_retval)
void GetCMSDefault_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvCMS_tunel_t color_tunel_type, int cmock_to_return);
#define GetDolbyModeIndex_ExpectAndReturn(dolbyMode, cmock_retval) GetDolbyModeIndex_CMockExpectAndReturn(__LINE__, dolbyMode, cmock_retval)
void GetDolbyModeIndex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* dolbyMode, int cmock_to_return);
#define ConvertVideoFormatToHDRFormat_ExpectAndReturn(videoFormat, cmock_retval) ConvertVideoFormatToHDRFormat_CMockExpectAndReturn(__LINE__, videoFormat, cmock_retval)
void ConvertVideoFormatToHDRFormat_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvVideoHDRFormat_t videoFormat, int cmock_to_return);
#define ConvertTVColorToVendorColor_ExpectAndReturn(blComponentColor, cmock_retval) ConvertTVColorToVendorColor_CMockExpectAndReturn(__LINE__, blComponentColor, cmock_retval)
void ConvertTVColorToVendorColor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataComponentColor_t blComponentColor, int cmock_to_return);
#define ConvertHDRFormatToContentFormat_ExpectAndReturn(hdrFormat, cmock_retval) ConvertHDRFormatToContentFormat_CMockExpectAndReturn(__LINE__, hdrFormat, cmock_retval)
void ConvertHDRFormatToContentFormat_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvhdr_type_t hdrFormat, int cmock_to_return);
#define GetCustomPQModeIndex_ExpectAndReturn(cmock_retval) GetCustomPQModeIndex_CMockExpectAndReturn(__LINE__, cmock_retval)
void GetCustomPQModeIndex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define SetCMSState_ExpectAndReturn(tunelType, colorType, componentState, cmock_retval) SetCMSState_CMockExpectAndReturn(__LINE__, tunelType, colorType, componentState, cmock_retval)
void SetCMSState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvCMS_tunel_t tunelType, tvcomponent_color_type_t colorType, tvcomponent_state_t componentState, tvError_t cmock_to_return);
#define isWBUserDfault_ExpectAndReturn(wbvalue, cmock_retval) isWBUserDfault_CMockExpectAndReturn(__LINE__, wbvalue, cmock_retval)
void isWBUserDfault_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataColor_t wbvalue, bool cmock_to_return);
#define GetWBRgbType_ExpectAndReturn(color, ctrl, cmock_retval) GetWBRgbType_CMockExpectAndReturn(__LINE__, color, ctrl, cmock_retval)
void GetWBRgbType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* color, const char* ctrl, int cmock_to_return);
#define GetUSerWBValueOnInit_ExpectAndReturn(cmock_retval) GetUSerWBValueOnInit_CMockExpectAndReturn(__LINE__, cmock_retval)
void GetUSerWBValueOnInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataColor_t cmock_to_return);
#define areEqual_ExpectAndReturn(wbvalueThis, wbvalueThat, cmock_retval) areEqual_CMockExpectAndReturn(__LINE__, wbvalueThis, wbvalueThat, cmock_retval)
void areEqual_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvDataColor_t wbvalueThis, tvDataColor_t wbvalueThat, bool cmock_to_return);
#define SetColorTemperatureUser_ExpectAndReturn(rgbType, value, cmock_retval) SetColorTemperatureUser_CMockExpectAndReturn(__LINE__, rgbType, value, cmock_retval)
void SetColorTemperatureUser_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int rgbType, int value, tvError_t cmock_to_return);
#define SaveColorTemperatureUser_ExpectAndReturn(rgbType, value, cmock_retval) SaveColorTemperatureUser_CMockExpectAndReturn(__LINE__, rgbType, value, cmock_retval)
void SaveColorTemperatureUser_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int rgbType, int value, tvError_t cmock_to_return);
#define SetBacklightInfo_ExpectAndReturn(backlightDefaults, cmock_retval) SetBacklightInfo_CMockExpectAndReturn(__LINE__, backlightDefaults, cmock_retval)
void SetBacklightInfo_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvBacklightInfo_t backlightDefaults, tvError_t cmock_to_return);
#define GetDriverEquivalentBLForCurrentFmt_ExpectAndReturn(backlight, cmock_retval) GetDriverEquivalentBLForCurrentFmt_CMockExpectAndReturn(__LINE__, backlight, cmock_retval)
void GetDriverEquivalentBLForCurrentFmt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int backlight, int cmock_to_return);
#define GetHLGModeIndex_ExpectAndReturn(hlgMode, cmock_retval) GetHLGModeIndex_CMockExpectAndReturn(__LINE__, hlgMode, cmock_retval)
void GetHLGModeIndex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* hlgMode, int cmock_to_return);
#define GetHDR10ModeIndex_ExpectAndReturn(hdr10Mode, cmock_retval) GetHDR10ModeIndex_CMockExpectAndReturn(__LINE__, hdr10Mode, cmock_retval)
void GetHDR10ModeIndex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* hdr10Mode, int cmock_to_return);
#define SetBacklightFade_ExpectAndReturn(from, to, duration, cmock_retval) SetBacklightFade_CMockExpectAndReturn(__LINE__, from, to, duration, cmock_retval)
void SetBacklightFade_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int from, int to, int duration, tvError_t cmock_to_return);
#define ReadAllModeConfigfile_ExpectAndReturn(file, cpybuffer, searchstring, cmock_retval) ReadAllModeConfigfile_CMockExpectAndReturn(__LINE__, file, cpybuffer, searchstring, cmock_retval)
void ReadAllModeConfigfile_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* file, char* cpybuffer, const char* searchstring, tvError_t cmock_to_return);
#define splitstringsfrombuffer_Expect(buffer, availableModes, totalcount) splitstringsfrombuffer_CMockExpect(__LINE__, buffer, availableModes, totalcount)
void splitstringsfrombuffer_CMockExpect(UNITY_LINE_TYPE cmock_line, char* buffer, char* availableModes, unsigned short* totalcount);
#define splitstringsandvaluefrombuffer_Expect(buffer, availableModes, totalcount) splitstringsandvaluefrombuffer_CMockExpect(__LINE__, buffer, availableModes, totalcount)
void splitstringsandvaluefrombuffer_CMockExpect(UNITY_LINE_TYPE cmock_line, char* buffer, pic_modes_t** availableModes, unsigned short* totalcount);
#define SetGammaMode_ExpectAndReturn(mode, cmock_retval) SetGammaMode_CMockExpectAndReturn(__LINE__, mode, cmock_retval)
void SetGammaMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int mode, tvError_t cmock_to_return);
#define SetLocalDimmingLevel_ExpectAndReturn(localDimmingLevel, cmock_retval) SetLocalDimmingLevel_CMockExpectAndReturn(__LINE__, localDimmingLevel, cmock_retval)
void SetLocalDimmingLevel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int localDimmingLevel, tvError_t cmock_to_return);
#define GetLocalDimmingLevel_ExpectAndReturn(localDimmingLevel, cmock_retval) GetLocalDimmingLevel_CMockExpectAndReturn(__LINE__, localDimmingLevel, cmock_retval)
void GetLocalDimmingLevel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* localDimmingLevel, tvError_t cmock_to_return);
#define SaveLocalDimmingLevel_ExpectAndReturn(sourceInput, pq_mode, hdr_type, value, cmock_retval) SaveLocalDimmingLevel_CMockExpectAndReturn(__LINE__, sourceInput, pq_mode, hdr_type, value, cmock_retval)
void SaveLocalDimmingLevel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int sourceInput, int pq_mode, int hdr_type, int value, tvError_t cmock_to_return);
#define SwitchEDID_Expect(pqmode) SwitchEDID_CMockExpect(__LINE__, pqmode)
void SwitchEDID_CMockExpect(UNITY_LINE_TYPE cmock_line, int pqmode);
#define UpdateEDIDAndSetDimmingLevel_ExpectAndReturn(dimmingLevel, cmock_retval) UpdateEDIDAndSetDimmingLevel_CMockExpectAndReturn(__LINE__, dimmingLevel, cmock_retval)
void UpdateEDIDAndSetDimmingLevel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int dimmingLevel, tvError_t cmock_to_return);
#define GetLDIMAndEDIDLevel_Expect(dimmingMode, format, dimmingLevel, edidLevel) GetLDIMAndEDIDLevel_CMockExpect(__LINE__, dimmingMode, format, dimmingLevel, edidLevel)
void GetLDIMAndEDIDLevel_CMockExpect(UNITY_LINE_TYPE cmock_line, int dimmingMode, int format, int* dimmingLevel, int* edidLevel);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
