/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktv_settings_hal.h"

static const char* CMockString_ReadCustWBvaluesFromDriverOnInit = "ReadCustWBvaluesFromDriverOnInit";
static const char* CMockString_TVUpdateRawBacklight = "TVUpdateRawBacklight";
static const char* CMockString_TVWriteSysfs = "TVWriteSysfs";
static const char* CMockString_cmd = "cmd";
static const char* CMockString_color = "color";
static const char* CMockString_ctrl = "ctrl";
static const char* CMockString_getRgbType = "getRgbType";
static const char* CMockString_midPointValue = "midPointValue";
static const char* CMockString_offset = "offset";
static const char* CMockString_path = "path";
static const char* CMockString_sourceIdFromOffset = "sourceIdFromOffset";
static const char* CMockString_tvCopySD3DatatoCridataEx = "tvCopySD3DatatoCridataEx";
static const char* CMockString_value = "value";

typedef struct _CMOCK_TVWriteSysfs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_path;
  const char* Expected_cmd;

} CMOCK_TVWriteSysfs_CALL_INSTANCE;

typedef struct _CMOCK_sourceIdFromOffset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  colortemperature_source_offset_t Expected_offset;

} CMOCK_sourceIdFromOffset_CALL_INSTANCE;

typedef struct _CMOCK_tvCopySD3DatatoCridataEx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_tvCopySD3DatatoCridataEx_CALL_INSTANCE;

typedef struct _CMOCK_ReadCustWBvaluesFromDriverOnInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  tvError_t ReturnVal;

} CMOCK_ReadCustWBvaluesFromDriverOnInit_CALL_INSTANCE;

typedef struct _CMOCK_getRgbType_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  char* Expected_color;
  char* Expected_ctrl;

} CMOCK_getRgbType_CALL_INSTANCE;

typedef struct _CMOCK_TVUpdateRawBacklight_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  tvError_t ReturnVal;
  int Expected_value;
  int Expected_midPointValue;

} CMOCK_TVUpdateRawBacklight_CALL_INSTANCE;

static struct Mocktv_settings_halInstance
{
  CMOCK_MEM_INDEX_TYPE TVWriteSysfs_CallInstance;
  CMOCK_MEM_INDEX_TYPE sourceIdFromOffset_CallInstance;
  CMOCK_MEM_INDEX_TYPE tvCopySD3DatatoCridataEx_CallInstance;
  CMOCK_MEM_INDEX_TYPE ReadCustWBvaluesFromDriverOnInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE getRgbType_CallInstance;
  CMOCK_MEM_INDEX_TYPE TVUpdateRawBacklight_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocktv_settings_hal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.TVWriteSysfs_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TVWriteSysfs);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.sourceIdFromOffset_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_sourceIdFromOffset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.tvCopySD3DatatoCridataEx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_tvCopySD3DatatoCridataEx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.ReadCustWBvaluesFromDriverOnInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ReadCustWBvaluesFromDriverOnInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.getRgbType_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_getRgbType);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.TVUpdateRawBacklight_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TVUpdateRawBacklight);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mocktv_settings_hal_Init(void)
{
  Mocktv_settings_hal_Destroy();
}

void Mocktv_settings_hal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int TVWriteSysfs(const char* path, const char* cmd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TVWriteSysfs_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TVWriteSysfs);
  cmock_call_instance = (CMOCK_TVWriteSysfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TVWriteSysfs_CallInstance);
  Mock.TVWriteSysfs_CallInstance = CMock_Guts_MemNext(Mock.TVWriteSysfs_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_TVWriteSysfs,CMockString_path);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_path, path, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_TVWriteSysfs,CMockString_cmd);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_cmd, cmd, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_TVWriteSysfs(CMOCK_TVWriteSysfs_CALL_INSTANCE* cmock_call_instance, const char* path, const char* cmd);
void CMockExpectParameters_TVWriteSysfs(CMOCK_TVWriteSysfs_CALL_INSTANCE* cmock_call_instance, const char* path, const char* cmd)
{
  cmock_call_instance->Expected_path = path;
  cmock_call_instance->Expected_cmd = cmd;
}

void TVWriteSysfs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* path, const char* cmd, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TVWriteSysfs_CALL_INSTANCE));
  CMOCK_TVWriteSysfs_CALL_INSTANCE* cmock_call_instance = (CMOCK_TVWriteSysfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TVWriteSysfs_CallInstance = CMock_Guts_MemChain(Mock.TVWriteSysfs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_TVWriteSysfs(cmock_call_instance, path, cmd);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int sourceIdFromOffset(colortemperature_source_offset_t offset)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sourceIdFromOffset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sourceIdFromOffset);
  cmock_call_instance = (CMOCK_sourceIdFromOffset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sourceIdFromOffset_CallInstance);
  Mock.sourceIdFromOffset_CallInstance = CMock_Guts_MemNext(Mock.sourceIdFromOffset_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_sourceIdFromOffset,CMockString_offset);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_offset), (void*)(&offset), sizeof(colortemperature_source_offset_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sourceIdFromOffset(CMOCK_sourceIdFromOffset_CALL_INSTANCE* cmock_call_instance, colortemperature_source_offset_t offset);
void CMockExpectParameters_sourceIdFromOffset(CMOCK_sourceIdFromOffset_CALL_INSTANCE* cmock_call_instance, colortemperature_source_offset_t offset)
{
  memcpy((void*)(&cmock_call_instance->Expected_offset), (void*)(&offset),
         sizeof(colortemperature_source_offset_t[sizeof(offset) == sizeof(colortemperature_source_offset_t) ? 1 : -1])); /* add colortemperature_source_offset_t to :treat_as_array if this causes an error */
}

void sourceIdFromOffset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, colortemperature_source_offset_t offset, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sourceIdFromOffset_CALL_INSTANCE));
  CMOCK_sourceIdFromOffset_CALL_INSTANCE* cmock_call_instance = (CMOCK_sourceIdFromOffset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sourceIdFromOffset_CallInstance = CMock_Guts_MemChain(Mock.sourceIdFromOffset_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sourceIdFromOffset(cmock_call_instance, offset);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void tvCopySD3DatatoCridataEx(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_tvCopySD3DatatoCridataEx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_tvCopySD3DatatoCridataEx);
  cmock_call_instance = (CMOCK_tvCopySD3DatatoCridataEx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.tvCopySD3DatatoCridataEx_CallInstance);
  Mock.tvCopySD3DatatoCridataEx_CallInstance = CMock_Guts_MemNext(Mock.tvCopySD3DatatoCridataEx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void tvCopySD3DatatoCridataEx_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tvCopySD3DatatoCridataEx_CALL_INSTANCE));
  CMOCK_tvCopySD3DatatoCridataEx_CALL_INSTANCE* cmock_call_instance = (CMOCK_tvCopySD3DatatoCridataEx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tvCopySD3DatatoCridataEx_CallInstance = CMock_Guts_MemChain(Mock.tvCopySD3DatatoCridataEx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

tvError_t ReadCustWBvaluesFromDriverOnInit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ReadCustWBvaluesFromDriverOnInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ReadCustWBvaluesFromDriverOnInit);
  cmock_call_instance = (CMOCK_ReadCustWBvaluesFromDriverOnInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ReadCustWBvaluesFromDriverOnInit_CallInstance);
  Mock.ReadCustWBvaluesFromDriverOnInit_CallInstance = CMock_Guts_MemNext(Mock.ReadCustWBvaluesFromDriverOnInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void ReadCustWBvaluesFromDriverOnInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvError_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ReadCustWBvaluesFromDriverOnInit_CALL_INSTANCE));
  CMOCK_ReadCustWBvaluesFromDriverOnInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_ReadCustWBvaluesFromDriverOnInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ReadCustWBvaluesFromDriverOnInit_CallInstance = CMock_Guts_MemChain(Mock.ReadCustWBvaluesFromDriverOnInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(tvError_t[sizeof(cmock_to_return) == sizeof(tvError_t) ? 1 : -1])); /* add tvError_t to :treat_as_array if this causes an error */
}

int getRgbType(char* color, char* ctrl)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getRgbType_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_getRgbType);
  cmock_call_instance = (CMOCK_getRgbType_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getRgbType_CallInstance);
  Mock.getRgbType_CallInstance = CMock_Guts_MemNext(Mock.getRgbType_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_getRgbType,CMockString_color);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_color, color, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getRgbType,CMockString_ctrl);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_ctrl, ctrl, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_getRgbType(CMOCK_getRgbType_CALL_INSTANCE* cmock_call_instance, char* color, char* ctrl);
void CMockExpectParameters_getRgbType(CMOCK_getRgbType_CALL_INSTANCE* cmock_call_instance, char* color, char* ctrl)
{
  cmock_call_instance->Expected_color = color;
  cmock_call_instance->Expected_ctrl = ctrl;
}

void getRgbType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* color, char* ctrl, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getRgbType_CALL_INSTANCE));
  CMOCK_getRgbType_CALL_INSTANCE* cmock_call_instance = (CMOCK_getRgbType_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getRgbType_CallInstance = CMock_Guts_MemChain(Mock.getRgbType_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_getRgbType(cmock_call_instance, color, ctrl);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

tvError_t TVUpdateRawBacklight(int value, int midPointValue)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TVUpdateRawBacklight_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TVUpdateRawBacklight);
  cmock_call_instance = (CMOCK_TVUpdateRawBacklight_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TVUpdateRawBacklight_CallInstance);
  Mock.TVUpdateRawBacklight_CallInstance = CMock_Guts_MemNext(Mock.TVUpdateRawBacklight_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_TVUpdateRawBacklight,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_value, value, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_TVUpdateRawBacklight,CMockString_midPointValue);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_midPointValue, midPointValue, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_TVUpdateRawBacklight(CMOCK_TVUpdateRawBacklight_CALL_INSTANCE* cmock_call_instance, int value, int midPointValue);
void CMockExpectParameters_TVUpdateRawBacklight(CMOCK_TVUpdateRawBacklight_CALL_INSTANCE* cmock_call_instance, int value, int midPointValue)
{
  cmock_call_instance->Expected_value = value;
  cmock_call_instance->Expected_midPointValue = midPointValue;
}

void TVUpdateRawBacklight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int value, int midPointValue, tvError_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TVUpdateRawBacklight_CALL_INSTANCE));
  CMOCK_TVUpdateRawBacklight_CALL_INSTANCE* cmock_call_instance = (CMOCK_TVUpdateRawBacklight_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TVUpdateRawBacklight_CallInstance = CMock_Guts_MemChain(Mock.TVUpdateRawBacklight_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_TVUpdateRawBacklight(cmock_call_instance, value, midPointValue);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(tvError_t[sizeof(cmock_to_return) == sizeof(tvError_t) ? 1 : -1])); /* add tvError_t to :treat_as_array if this causes an error */
}

