/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTV_SETTINGS_HAL_H
#define _MOCKTV_SETTINGS_HAL_H

#include "unity.h"
#include "tv_settings_hal.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocktv_settings_hal_Init(void);
void Mocktv_settings_hal_Destroy(void);
void Mocktv_settings_hal_Verify(void);




#define TVWriteSysfs_ExpectAndReturn(path, cmd, cmock_retval) TVWriteSysfs_CMockExpectAndReturn(__LINE__, path, cmd, cmock_retval)
void TVWriteSysfs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* path, const char* cmd, int cmock_to_return);
#define sourceIdFromOffset_ExpectAndReturn(offset, cmock_retval) sourceIdFromOffset_CMockExpectAndReturn(__LINE__, offset, cmock_retval)
void sourceIdFromOffset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, colortemperature_source_offset_t offset, int cmock_to_return);
#define tvCopySD3DatatoCridataEx_Expect() tvCopySD3DatatoCridataEx_CMockExpect(__LINE__)
void tvCopySD3DatatoCridataEx_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define ReadCustWBvaluesFromDriverOnInit_ExpectAndReturn(cmock_retval) ReadCustWBvaluesFromDriverOnInit_CMockExpectAndReturn(__LINE__, cmock_retval)
void ReadCustWBvaluesFromDriverOnInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, tvError_t cmock_to_return);
#define getRgbType_ExpectAndReturn(color, ctrl, cmock_retval) getRgbType_CMockExpectAndReturn(__LINE__, color, ctrl, cmock_retval)
void getRgbType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* color, char* ctrl, int cmock_to_return);
#define TVUpdateRawBacklight_ExpectAndReturn(value, midPointValue, cmock_retval) TVUpdateRawBacklight_CMockExpectAndReturn(__LINE__, value, midPointValue, cmock_retval)
void TVUpdateRawBacklight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int value, int midPointValue, tvError_t cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
