/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockautoBacklightControl.h"

static const char* CMockString_autoBacklightControl = "autoBacklightControl";
static const char* CMockString_autoBacklightThreadInit = "autoBacklightThreadInit";
static const char* CMockString_autoBacklightThreadTerm = "autoBacklightThreadTerm";
static const char* CMockString_blReadSysfs = "blReadSysfs";
static const char* CMockString_blWriteSysfs = "blWriteSysfs";
static const char* CMockString_enable = "enable";
static const char* CMockString_path = "path";
static const char* CMockString_value = "value";

typedef struct _CMOCK_blWriteSysfs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_path;
  int Expected_value;

} CMOCK_blWriteSysfs_CALL_INSTANCE;

typedef struct _CMOCK_blReadSysfs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const char* Expected_path;

} CMOCK_blReadSysfs_CALL_INSTANCE;

typedef struct _CMOCK_autoBacklightThreadInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_autoBacklightThreadInit_CALL_INSTANCE;

typedef struct _CMOCK_autoBacklightThreadTerm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_autoBacklightThreadTerm_CALL_INSTANCE;

typedef struct _CMOCK_autoBacklightControl_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  bool Expected_enable;

} CMOCK_autoBacklightControl_CALL_INSTANCE;

static struct MockautoBacklightControlInstance
{
  CMOCK_MEM_INDEX_TYPE blWriteSysfs_CallInstance;
  CMOCK_MEM_INDEX_TYPE blReadSysfs_CallInstance;
  CMOCK_MEM_INDEX_TYPE autoBacklightThreadInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE autoBacklightThreadTerm_CallInstance;
  CMOCK_MEM_INDEX_TYPE autoBacklightControl_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockautoBacklightControl_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.blWriteSysfs_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blWriteSysfs);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.blReadSysfs_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blReadSysfs);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.autoBacklightThreadInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_autoBacklightThreadInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.autoBacklightThreadTerm_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_autoBacklightThreadTerm);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.autoBacklightControl_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_autoBacklightControl);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void MockautoBacklightControl_Init(void)
{
  MockautoBacklightControl_Destroy();
}

void MockautoBacklightControl_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int blWriteSysfs(const char* path, int value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blWriteSysfs_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blWriteSysfs);
  cmock_call_instance = (CMOCK_blWriteSysfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blWriteSysfs_CallInstance);
  Mock.blWriteSysfs_CallInstance = CMock_Guts_MemNext(Mock.blWriteSysfs_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blWriteSysfs,CMockString_path);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_path, path, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blWriteSysfs,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_value, value, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_blWriteSysfs(CMOCK_blWriteSysfs_CALL_INSTANCE* cmock_call_instance, const char* path, int value);
void CMockExpectParameters_blWriteSysfs(CMOCK_blWriteSysfs_CALL_INSTANCE* cmock_call_instance, const char* path, int value)
{
  cmock_call_instance->Expected_path = path;
  cmock_call_instance->Expected_value = value;
}

void blWriteSysfs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* path, int value, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blWriteSysfs_CALL_INSTANCE));
  CMOCK_blWriteSysfs_CALL_INSTANCE* cmock_call_instance = (CMOCK_blWriteSysfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blWriteSysfs_CallInstance = CMock_Guts_MemChain(Mock.blWriteSysfs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blWriteSysfs(cmock_call_instance, path, value);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int blReadSysfs(const char* path)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blReadSysfs_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blReadSysfs);
  cmock_call_instance = (CMOCK_blReadSysfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blReadSysfs_CallInstance);
  Mock.blReadSysfs_CallInstance = CMock_Guts_MemNext(Mock.blReadSysfs_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blReadSysfs,CMockString_path);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_path, path, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_blReadSysfs(CMOCK_blReadSysfs_CALL_INSTANCE* cmock_call_instance, const char* path);
void CMockExpectParameters_blReadSysfs(CMOCK_blReadSysfs_CALL_INSTANCE* cmock_call_instance, const char* path)
{
  cmock_call_instance->Expected_path = path;
}

void blReadSysfs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* path, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blReadSysfs_CALL_INSTANCE));
  CMOCK_blReadSysfs_CALL_INSTANCE* cmock_call_instance = (CMOCK_blReadSysfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blReadSysfs_CallInstance = CMock_Guts_MemChain(Mock.blReadSysfs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blReadSysfs(cmock_call_instance, path);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int autoBacklightThreadInit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_autoBacklightThreadInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_autoBacklightThreadInit);
  cmock_call_instance = (CMOCK_autoBacklightThreadInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.autoBacklightThreadInit_CallInstance);
  Mock.autoBacklightThreadInit_CallInstance = CMock_Guts_MemNext(Mock.autoBacklightThreadInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void autoBacklightThreadInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_autoBacklightThreadInit_CALL_INSTANCE));
  CMOCK_autoBacklightThreadInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_autoBacklightThreadInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.autoBacklightThreadInit_CallInstance = CMock_Guts_MemChain(Mock.autoBacklightThreadInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int autoBacklightThreadTerm(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_autoBacklightThreadTerm_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_autoBacklightThreadTerm);
  cmock_call_instance = (CMOCK_autoBacklightThreadTerm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.autoBacklightThreadTerm_CallInstance);
  Mock.autoBacklightThreadTerm_CallInstance = CMock_Guts_MemNext(Mock.autoBacklightThreadTerm_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void autoBacklightThreadTerm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_autoBacklightThreadTerm_CALL_INSTANCE));
  CMOCK_autoBacklightThreadTerm_CALL_INSTANCE* cmock_call_instance = (CMOCK_autoBacklightThreadTerm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.autoBacklightThreadTerm_CallInstance = CMock_Guts_MemChain(Mock.autoBacklightThreadTerm_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int autoBacklightControl(bool enable)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_autoBacklightControl_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_autoBacklightControl);
  cmock_call_instance = (CMOCK_autoBacklightControl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.autoBacklightControl_CallInstance);
  Mock.autoBacklightControl_CallInstance = CMock_Guts_MemNext(Mock.autoBacklightControl_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_autoBacklightControl,CMockString_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enable, enable, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_autoBacklightControl(CMOCK_autoBacklightControl_CALL_INSTANCE* cmock_call_instance, bool enable);
void CMockExpectParameters_autoBacklightControl(CMOCK_autoBacklightControl_CALL_INSTANCE* cmock_call_instance, bool enable)
{
  cmock_call_instance->Expected_enable = enable;
}

void autoBacklightControl_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool enable, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_autoBacklightControl_CALL_INSTANCE));
  CMOCK_autoBacklightControl_CALL_INSTANCE* cmock_call_instance = (CMOCK_autoBacklightControl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.autoBacklightControl_CallInstance = CMock_Guts_MemChain(Mock.autoBacklightControl_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_autoBacklightControl(cmock_call_instance, enable);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

